name: Noah Dayan
markdown: kramdown
highlighter: pygments
exclude: ["README.md", "Gemfile", "Gemfile.lock", "CNAME"]
timezone: America/Montreal

prose:
  rooturl: '_posts'
  siteurl: 'http://www.noahdayan.com'
  media: 'media'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
