name: Noah Dayan
exclude: ["README.md", "Gemfile", "Gemfile.lock", "CNAME"]
timezone: Europe/London
url: http://www.noahdayan.com

s3url: https://s3.amazonaws.com/noahdayan

plugins:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
