name: Noah Dayan
exclude: ["README.md", "Gemfile", "Gemfile.lock", "CNAME"]
timezone: Europe/London

s3url: https://s3.amazonaws.com/noahdayan

gems:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
